version: '3.8'

services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    command: >
      bash -c "python3 wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      POSTGRES_CHECK_TIMEOUT: ${POSTGRES_CHECK_TIMEOUT}
      POSTGRES_CHECK_INTERVAL: ${POSTGRES_CHECK_INTERVAL}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  documentation:
    build: .
    command: "python3 -m mkdocs serve --dev-addr=0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    restart: always

volumes:
  postgres_data:
