site_name: online_lab_app
site_description: Backend for the Online Lab Application
repo_url: https://github.com/rakati/online_lab_app
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/rakati">rakati</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
