# Generated by Django 5.1.3 on 2025-01-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_lab_instructions_lab_packages_lab_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='labs/'),
        ),
        migrations.AddField(
            model_name='lab',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
