# Generated by Django 5.1.3 on 2025-01-31 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_lab_image_lab_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_labs', to=settings.AUTH_USER_MODEL),
        ),
    ]
