# Generated by Django 5.1.3 on 2025-02-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_lab_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='lab',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('fr', 'French'), ('ar', 'Arabic')], default='eng', max_length=10),
        ),
        migrations.AddField(
            model_name='lab',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills relevant to the lab.'),
        ),
        migrations.AddField(
            model_name='lab',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lab',
            name='time',
            field=models.PositiveIntegerField(blank=True, help_text='Time in minutes for the lab.', null=True),
        ),
    ]
